### ISSUE TITLE
Export `Card`, `Badge` and `Alert` from ChakraUI

### ISSUE THREAD

**Issue by oohwooh** [codeday/topo#17]
In https://github.com/codeday/www-clear, we have a super useful `InfoBox` component. I think this would be good to add as a molecule. 

https://github.com/codeday/www-clear/blob/master/src/components/InfoBox.js

There are probably some changes we can make to make it even more helpful, pretty, and flexible, but brainstorming is needed on that.

Example (every panel in this page is an `InfoBox`):
![image](https://user-images.githubusercontent.com/11283815/192055644-2b324bba-d997-4af1-ae83-73f9825a7350.png)

**Comment by oohwooh** [comment]
Other components that would be awesome to have as native in topo:
[Alert](https://github.com/codeday/www-clear/blob/master/src/components/Alert.js)
[Badge](https://github.com/codeday/www-clear/blob/master/src/components/Badge.js)

**Comment by oohwooh** [comment]
Chakra UI has recently added [Card](https://chakra-ui.com/docs/components/card), [Badge](https://chakra-ui.com/docs/components/badge), and [Alert](https://chakra-ui.com/docs/components/alert) components, which are pretty much exactly what is desired in this case. A pull request would be welcome to export these as `Atom`s

**Comment by buenobunny** [comment]
It seems as though ChakraUI will have to be [migrated to v2](https://chakra-ui.com/getting-started/migration) for the Card, Badge and Alert. [Card only shows up in v2.1.0+ ](https://www.npmjs.com/package/@chakra-ui/card?activeTab=versions)

**Comment by buenobunny** [comment]
Issue closed by PR #29
